name: power_server
description: A REST API framework. Light and powerful. Taking advantage of the alfred package. Provided by the Avicenna group.
version: 0.1.6
repository: https://github.com/avicenna/power_server

environment:
  sdk: '>=3.9.0'

dependencies:
  mime: ^2.0.0
  mime_type: ^1.0.1
  queue: any
  path: any
  meta: any

dev_dependencies:
  test: any
  web_socket_channel: any
  http: any
  lints: any
